// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenericMessage.proto

package proto;

public final class GenericMessageProto {
  private GenericMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GenericMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GenericMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.GenericMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.GenericMessage.Type type = 1;</code>
     */
    proto.GenericMessageProto.GenericMessage.Type getType();

    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    boolean hasChatMessage();
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessage getChatMessage();
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder();

    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    boolean hasQuery();
    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    proto.QueryProto.Query getQuery();
    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    proto.QueryProto.QueryOrBuilder getQueryOrBuilder();
  }
  /**
   * Protobuf type {@code proto.GenericMessage}
   */
  public static final class GenericMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.GenericMessage)
      GenericMessageOrBuilder {
    // Use GenericMessage.newBuilder() to construct.
    private GenericMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GenericMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GenericMessage defaultInstance;
    public static GenericMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GenericMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GenericMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.GenericMessageProto.GenericMessage.Type value = proto.GenericMessageProto.GenericMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              proto.ChatMessageProto.ChatMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = chatMessage_.toBuilder();
              }
              chatMessage_ = input.readMessage(proto.ChatMessageProto.ChatMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMessage_);
                chatMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              proto.QueryProto.Query.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = query_.toBuilder();
              }
              query_ = input.readMessage(proto.QueryProto.Query.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(query_);
                query_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GenericMessageProto.internal_static_proto_GenericMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GenericMessageProto.internal_static_proto_GenericMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GenericMessageProto.GenericMessage.class, proto.GenericMessageProto.GenericMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GenericMessage> PARSER =
        new com.google.protobuf.AbstractParser<GenericMessage>() {
      public GenericMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenericMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GenericMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code proto.GenericMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT_MESSAGE = 1;</code>
       */
      CHAT_MESSAGE(0, 1),
      /**
       * <code>QUERY = 2;</code>
       */
      QUERY(1, 2),
      ;

      /**
       * <code>CHAT_MESSAGE = 1;</code>
       */
      public static final int CHAT_MESSAGE_VALUE = 1;
      /**
       * <code>QUERY = 2;</code>
       */
      public static final int QUERY_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return CHAT_MESSAGE;
          case 2: return QUERY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.GenericMessageProto.GenericMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.GenericMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private proto.GenericMessageProto.GenericMessage.Type type_;
    /**
     * <code>required .proto.GenericMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.GenericMessage.Type type = 1;</code>
     */
    public proto.GenericMessageProto.GenericMessage.Type getType() {
      return type_;
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 2;
    private proto.ChatMessageProto.ChatMessage chatMessage_;
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public boolean hasChatMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessage getChatMessage() {
      return chatMessage_;
    }
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder() {
      return chatMessage_;
    }

    public static final int QUERY_FIELD_NUMBER = 3;
    private proto.QueryProto.Query query_;
    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    public proto.QueryProto.Query getQuery() {
      return query_;
    }
    /**
     * <code>optional .proto.Query query = 3;</code>
     */
    public proto.QueryProto.QueryOrBuilder getQueryOrBuilder() {
      return query_;
    }

    private void initFields() {
      type_ = proto.GenericMessageProto.GenericMessage.Type.CHAT_MESSAGE;
      chatMessage_ = proto.ChatMessageProto.ChatMessage.getDefaultInstance();
      query_ = proto.QueryProto.Query.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasChatMessage()) {
        if (!getChatMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasQuery()) {
        if (!getQuery().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, chatMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, query_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chatMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, query_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.GenericMessageProto.GenericMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.GenericMessageProto.GenericMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.GenericMessageProto.GenericMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.GenericMessageProto.GenericMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.GenericMessageProto.GenericMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GenericMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GenericMessage)
        proto.GenericMessageProto.GenericMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GenericMessageProto.internal_static_proto_GenericMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GenericMessageProto.internal_static_proto_GenericMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GenericMessageProto.GenericMessage.class, proto.GenericMessageProto.GenericMessage.Builder.class);
      }

      // Construct using proto.GenericMessageProto.GenericMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChatMessageFieldBuilder();
          getQueryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = proto.GenericMessageProto.GenericMessage.Type.CHAT_MESSAGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chatMessageBuilder_ == null) {
          chatMessage_ = proto.ChatMessageProto.ChatMessage.getDefaultInstance();
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (queryBuilder_ == null) {
          query_ = proto.QueryProto.Query.getDefaultInstance();
        } else {
          queryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GenericMessageProto.internal_static_proto_GenericMessage_descriptor;
      }

      public proto.GenericMessageProto.GenericMessage getDefaultInstanceForType() {
        return proto.GenericMessageProto.GenericMessage.getDefaultInstance();
      }

      public proto.GenericMessageProto.GenericMessage build() {
        proto.GenericMessageProto.GenericMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GenericMessageProto.GenericMessage buildPartial() {
        proto.GenericMessageProto.GenericMessage result = new proto.GenericMessageProto.GenericMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (chatMessageBuilder_ == null) {
          result.chatMessage_ = chatMessage_;
        } else {
          result.chatMessage_ = chatMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (queryBuilder_ == null) {
          result.query_ = query_;
        } else {
          result.query_ = queryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GenericMessageProto.GenericMessage) {
          return mergeFrom((proto.GenericMessageProto.GenericMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GenericMessageProto.GenericMessage other) {
        if (other == proto.GenericMessageProto.GenericMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChatMessage()) {
          mergeChatMessage(other.getChatMessage());
        }
        if (other.hasQuery()) {
          mergeQuery(other.getQuery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasChatMessage()) {
          if (!getChatMessage().isInitialized()) {
            
            return false;
          }
        }
        if (hasQuery()) {
          if (!getQuery().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GenericMessageProto.GenericMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GenericMessageProto.GenericMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private proto.GenericMessageProto.GenericMessage.Type type_ = proto.GenericMessageProto.GenericMessage.Type.CHAT_MESSAGE;
      /**
       * <code>required .proto.GenericMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .proto.GenericMessage.Type type = 1;</code>
       */
      public proto.GenericMessageProto.GenericMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .proto.GenericMessage.Type type = 1;</code>
       */
      public Builder setType(proto.GenericMessageProto.GenericMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.GenericMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = proto.GenericMessageProto.GenericMessage.Type.CHAT_MESSAGE;
        onChanged();
        return this;
      }

      private proto.ChatMessageProto.ChatMessage chatMessage_ = proto.ChatMessageProto.ChatMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> chatMessageBuilder_;
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public boolean hasChatMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage getChatMessage() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_;
        } else {
          return chatMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMessage_ = value;
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(
          proto.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = builderForValue.build();
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder mergeChatMessage(proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              chatMessage_ != proto.ChatMessageProto.ChatMessage.getDefaultInstance()) {
            chatMessage_ =
              proto.ChatMessageProto.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
          } else {
            chatMessage_ = value;
          }
          onChanged();
        } else {
          chatMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = proto.ChatMessageProto.ChatMessage.getDefaultInstance();
          onChanged();
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage.Builder getChatMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getChatMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilder();
        } else {
          return chatMessage_;
        }
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> 
          getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder>(
                  getChatMessage(),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }

      private proto.QueryProto.Query query_ = proto.QueryProto.Query.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          proto.QueryProto.Query, proto.QueryProto.Query.Builder, proto.QueryProto.QueryOrBuilder> queryBuilder_;
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public proto.QueryProto.Query getQuery() {
        if (queryBuilder_ == null) {
          return query_;
        } else {
          return queryBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public Builder setQuery(proto.QueryProto.Query value) {
        if (queryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          query_ = value;
          onChanged();
        } else {
          queryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public Builder setQuery(
          proto.QueryProto.Query.Builder builderForValue) {
        if (queryBuilder_ == null) {
          query_ = builderForValue.build();
          onChanged();
        } else {
          queryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public Builder mergeQuery(proto.QueryProto.Query value) {
        if (queryBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              query_ != proto.QueryProto.Query.getDefaultInstance()) {
            query_ =
              proto.QueryProto.Query.newBuilder(query_).mergeFrom(value).buildPartial();
          } else {
            query_ = value;
          }
          onChanged();
        } else {
          queryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public Builder clearQuery() {
        if (queryBuilder_ == null) {
          query_ = proto.QueryProto.Query.getDefaultInstance();
          onChanged();
        } else {
          queryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public proto.QueryProto.Query.Builder getQueryBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getQueryFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      public proto.QueryProto.QueryOrBuilder getQueryOrBuilder() {
        if (queryBuilder_ != null) {
          return queryBuilder_.getMessageOrBuilder();
        } else {
          return query_;
        }
      }
      /**
       * <code>optional .proto.Query query = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.QueryProto.Query, proto.QueryProto.Query.Builder, proto.QueryProto.QueryOrBuilder> 
          getQueryFieldBuilder() {
        if (queryBuilder_ == null) {
          queryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.QueryProto.Query, proto.QueryProto.Query.Builder, proto.QueryProto.QueryOrBuilder>(
                  getQuery(),
                  getParentForChildren(),
                  isClean());
          query_ = null;
        }
        return queryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.GenericMessage)
    }

    static {
      defaultInstance = new GenericMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GenericMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GenericMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GenericMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GenericMessage.proto\022\005proto\032\013Query.pro" +
      "to\032\021ChatMessage.proto\"\245\001\n\016GenericMessage" +
      "\022(\n\004type\030\001 \002(\0162\032.proto.GenericMessage.Ty" +
      "pe\022\'\n\013chatMessage\030\002 \001(\0132\022.proto.ChatMess" +
      "age\022\033\n\005query\030\003 \001(\0132\014.proto.Query\"#\n\004Type" +
      "\022\020\n\014CHAT_MESSAGE\020\001\022\t\n\005QUERY\020\002B\034\n\005protoB\023" +
      "GenericMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.QueryProto.getDescriptor(),
          proto.ChatMessageProto.getDescriptor(),
        }, assigner);
    internal_static_proto_GenericMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_GenericMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_GenericMessage_descriptor,
        new java.lang.String[] { "Type", "ChatMessage", "Query", });
    proto.QueryProto.getDescriptor();
    proto.ChatMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
